const cervejas = [
  {
    codigo: 123,
    fabricante: 'Urquell',
    descricao: 'Pilsner Urquell 500ML',
    valor: 20,
    estoque: 200,
  },
  {
    codigo: 176,
    fabricante: 'Schornstein',
    descricao: 'Schornstein Imperial 500ML',
    valor: 35.99,
    estoque: 150,
  },
  {
    codigo: 122,
    fabricante: 'Schornstein',
    descricao: 'Schornstein IPA 500ML',
    valor: 18.99,
    estoque: 300,
  },
  {
    codigo: 323,
    fabricante: 'Maniacs',
    descricao: 'Maniacs Craft Lager 355ML',
    valor: 309.99,
    estoque: 500,
  },
  {
    codigo: 183,
    fabricante: 'Leuven',
    descricao: 'Leuven Red ALE Knight 600ML',
    valor: 25.99,
    estoque: 100,
  },
  {
    codigo: 129,
    fabricante: 'Leuven',
    descricao: 'Leuven Witbier The Witch 500ML',
    valor: 19.99,
    estoque: 200,
  },
  {
    codigo: 451,
    fabricante: 'Lupulus',
    descricao: 'Lupulus Blanche 330ML',
    valor: 29.99,
    estoque: 0,
  },
  {
    codigo: 111,
    fabricante: 'Eggenberg',
    descricao: 'Samichlaus Berrique 330ML',
    valor: 55.9,
    estoque: 25,
  },
  {
    codigo: 1,
    fabricante: 'Fuller',
    descricao: "Fuller's Vintage Ale 2015 500ML",
    valor: 264.9,
    estoque: 5,
  },
];

const clientes = [
  { nome: 'José', idade: 30, email: 'jose@bolo.com.br' },
  { nome: 'Maria', idade: 32, email: 'maria@gimail.com' },
  { nome: 'Kátia', idade: 17, email: 'katiac@gimail.com' },
  { nome: 'Samuel', idade: 16, email: 'samuel@hotwells.com' },
  { nome: 'Phillipe', idade: 21, email: 'phillipe@daiso.com' },
  { nome: 'Edmundo', idade: 14, email: 'edmundo@rota.com' },
  { nome: 'Tamires', idade: 25, email: 'tamiresf@tata.com' },
  { nome: 'Mariana', idade: 31, email: 'mariana@bolo.com.br' },
  { nome: 'Beatriz', idade: 18, email: 'beatriz@gugu.com' },
  { nome: 'Joseli', idade: 42, email: 'joseli@love.com' },
  { nome: 'Jefferson', idade: 12, email: 'jefferson@goal.com' },
  { nome: 'Luciana', idade: 41, email: 'luciana@alegria.com' },
];
module.exports = { cervejas, clientes };
